version: '3.8'

services:
  cafe_app:
    container_name: cafe_app
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head &&
                    uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
     - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy


  db:
    container_name: main-db
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5432" ]
      interval: 2s
      timeout: 2s
      retries: 3
    restart: always


  test-db:
    image: postgres:15.1-alpine
    container_name: test-db
    command: postgres -p 8080
    environment:
      POSTGRES_DB: postgres-test
      POSTGRES_USER: postgres-test
      POSTGRES_PASSWORD: postgres-test
    ports:
      - 8080:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 8080" ]
      interval: 2s
      timeout: 2s
      retries: 3


  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "pytest -v tests/"
    ports:
     - 6000:6000
    env_file:
      - .env.dev
    depends_on:
      test-db:
        condition: service_healthy
